# ./Taskfile.yaml
# See: https://taskfile.dev/api/  

version: "3"  

tasks:  
  default: # Если не указать конкретную команду, будут выполнены дефолтные
    cmds:  
      - task: generate  
  generate:  ## Команда для генерации
    aliases: ## Алиасы команды, для простоты использования
      - gen  
    desc: "Generate code from proto files"  
    cmds:  ## Тут описываем необходимые bash-команды
      - protoc -I proto proto/auth.proto --go_out=./gen/auth/ --go_opt=paths=source_relative --go-grpc_out=./gen/auth/ --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/store-giver.proto --go_out=./gen/store-giver/ --go_opt=paths=source_relative --go-grpc_out=./gen/store-giver/ --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/evostore-giver.proto --go_out=./gen/evostore-giver/ --go_opt=paths=source_relative --go-grpc_out=./gen/evostore-giver/ --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/evodevice-giver.proto --go_out=./gen/evodevice-giver/ --go_opt=paths=source_relative --go-grpc_out=./gen/evodevice-giver/ --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/evodoc-giver.proto --go_out=./gen/evodoc-giver/ --go_opt=paths=source_relative --go-grpc_out=./gen/evodoc-giver/ --go-grpc_opt=paths=source_relative